# Generated by Django 5.0 on 2024-05-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_to_become_member', models.TextField()),
                ('bank_details', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
            ],
        ),
    ]
