# Generated by Django 5.0 on 2024-05-02 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_up', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='about_photos/')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='about_us.aboutus')),
            ],
        ),
    ]
